type ActiveSession {
	user: User!
	startTime: DateTime!
}
input CreateDeviceInput {
	address: String!
	name: String!
}
"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime
input DayStatsInput {
	year: Int!
	month: Int!
	day: Int!
}
type Device {
	id: UUID!
	address: String!
	name: String!
}
input MonthStatsInput {
	year: Int!
	month: Int!
}
type MutationRoot {
	createDevice(data: CreateDeviceInput!): Device!
	updateDevice(id: UUID!, data: UpdateDeviceInput!): Device!
	deleteDevice(id: UUID!): Boolean!
}
enum Period {
	SUMMER
	LP1
	LP2
	LP3
	LP4
}
type QueryRoot {
	currentSessions: [ActiveSession!]!
	stats(input: StatsInput): [Stat!]!
	currentStudyPeriod: Period!
	me: User!
}
type Session {
	startTime: DateTime!
	endTime: DateTime!
}
type Stat {
	user: User!
	durationSeconds: Int!
}
input StatsInput {
	yearStats: YearStatsInput
	monthStats: MonthStatsInput
	dayStats: DayStatsInput
	studyYearStats: StudyYearStatsInput
	studyPeriodStats: StudyPeriodStatsInput
}
input StudyPeriodStatsInput {
	year: Int!
	period: Period!
}
input StudyYearStatsInput {
	year: Int!
}
type SubscriptionRoot {
	userJoin: ActiveSession!
	userLeave: User!
}
scalar UUID
input UpdateDeviceInput {
	name: String!
}
type User {
	id: UUID!
	cid: String!
	nick: String!
	firstName: String!
	lastName: String!
	avatarUrl: String!
	groups: [String!]!
	hourStats: [Int!]!
	recentSessions: [Session!]!
	longestSession: Session
	devices: [Device!]!
}
input YearStatsInput {
	year: Int!
}
schema {
	query: QueryRoot
	mutation: MutationRoot
	subscription: SubscriptionRoot
}

