type ActiveSession {
	user: User!
	startTime: DateTime!
}
"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime
type Device {
	id: UUID!
	address: String!
	name: String!
	isActive: Boolean!
}
input DeviceInput {
	address: String!
	name: String!
}
type MutationRoot {
	setDevices(data: SetDevicesInput!): [Device!]!
}
enum Period {
	SUMMER
	LP1
	LP2
	LP3
	LP4
}
type QueryRoot {
	currentSessions: [ActiveSession!]!
	statsAlltime: [Stat!]!
	statsStudyYear(input: StatsStudyYearInput): StatsStudyYearPayload!
	statsStudyPeriod(input: StatsStudyPeriodInput): StatsStudyPeriodPayload!
	statsMonth(input: StatsMonthInput): StatsMonthPayload!
	statsWeek(input: StatsWeekInput): StatsWeekPayload!
	statsDay(input: StatsDayInput): StatsDayPayload!
	me: User!
	user(input: UserUniqueInput!): User!
}
type Session {
	startTime: DateTime!
	endTime: DateTime!
}
input SetDevicesInput {
	devices: [DeviceInput!]!
}
type Stat {
	user: User!
	durationSeconds: Int!
	currentPosition: Int!
	prevPosition: Int
}
input StatsDayInput {
	year: Int!
	month: Int!
	day: Int!
}
type StatsDayPayload {
	stats: [Stat!]!
	curr: YearMonthDay!
	next: YearMonthDay!
	prev: YearMonthDay!
}
input StatsMonthInput {
	year: Int!
	month: Int!
}
type StatsMonthPayload {
	stats: [Stat!]!
	curr: YearMonth!
	next: YearMonth!
	prev: YearMonth!
}
input StatsStudyPeriodInput {
	year: Int!
	period: Period!
}
type StatsStudyPeriodPayload {
	stats: [Stat!]!
	year: Int!
	period: Period!
}
input StatsStudyYearInput {
	year: Int!
}
type StatsStudyYearPayload {
	stats: [Stat!]!
	year: Int!
}
input StatsWeekInput {
	year: Int!
	week: Int!
}
type StatsWeekPayload {
	stats: [Stat!]!
	curr: YearWeek!
	next: YearWeek!
	prev: YearWeek!
}
type SubscriptionRoot {
	userJoin: ActiveSession!
	userLeave: User!
}
scalar UUID
type User {
	id: UUID!
	cid: String!
	nick: String!
	firstName: String!
	lastName: String!
	avatarUrl: String!
	groups: [String!]!
	hourStats: [Int!]!
	recentSessions: [Session!]!
	longestSession: Session
	totalTimeSeconds: Int!
	devices: [Device!]!
}
input UserUniqueInput {
	id: UUID
	cid: String
}
type YearMonth {
	year: Int!
	month: Int!
}
type YearMonthDay {
	year: Int!
	month: Int!
	day: Int!
}
type YearWeek {
	year: Int!
	week: Int!
}
schema {
	query: QueryRoot
	mutation: MutationRoot
	subscription: SubscriptionRoot
}

